### ISSUE TITLE
License / Can I distribute this?

### ISSUE THREAD

**Issue by weichx** [Chlumsky/msdf-atlas-gen#1]
Hey, I've been using MSDF for a while now and really like it, thanks for sharing your great projects with the world! 

I'm working on a UI package for Unity and since I'm unhappy with Unity's fonts I wanted to ship with MSDF instead. Are there any restrictions that prevent me from distributing my package that bundles msdf and the generator within it to customers?

**Comment by Chlumsky** [comment]
There are no restrictions.
