### ISSUE TITLE
Cyrillic

### ISSUE THREAD

**Issue by liyanic** [Chlumsky/msdf-atlas-gen#101]
Hi,
When I try to create a Russian (Cyrillic) based atlas, I do not get the desired character. I use the hex code 0x44f for я, but I just get a 0 image as output. I use this command:
`msdf-atlas-gen.exe -font OpenSans_Condensed-Bold.ttf -glyphs 0x44f -type mtsdf -imageout test-russian.png -json test-russian.json`

However, when I try to create an image using msdfgen, it works:

`msdfgen.exe msdf -font OpenSans_Condensed-Bold.ttf 0x44f -o test.png`

Thanks for your help.

**Comment by Chlumsky** [comment]
Use `-chars 0x44f`, `-glyphs` is for glyph indices.

**Comment by liyanic** [comment]
Thanks a lot
