### ISSUE TITLE
Bug found in FontGeometry default constructor

### ISSUE THREAD

**Issue by MirrasHue** [Chlumsky/msdf-atlas-gen#108]
Hey, while I was trying to make use of the existing internal vector (ownGlyphs) in the FontGeometry class, for storing the glyphs (instead of providing an external one), I encountered some issues caused by the default constructor. Here is the commit message from my fork, that explains it in more detail:

- Make more use of the internal glyph vector in FontGeometry (ownGlyphs), by providing a way to retrieve it. (Useful when the user doesn't want to provide their own vector but still wants to apply edge coloring, for example).
- Fixed a bug in the default constructor of FontGeometry, caused by glyphs->size() occasionally returning large random values which are assigned to rangeStart and rangeEnd (probably because ownGlyphs didn't get fully initialized yet).
- Don't allow glyphs pointer to be initialized with nullptr (use ownGlyphs in this case). This also avoids undefined behavior because null checks are not performed before calling member functions through the _glyphs_ pointer.

A simple way to fix it without the additional functionality (retrieving the underlying glyph vector, or handling a null *glyphStorage parameter), is to simply initialize rangeStart and rangeEnd to 0 in the member initializer list of the default constructor.

Incorporating the other changes is pretty straight forward as well. As I modified my fork a little further, I don't know if I can open a pull request as easily, but you can check it out at https://github.com/MirrasHue/MSDF-Atlas-Gen/commit/a59e64e285df75334648078d8c0aedd03a2ce41e

Thank you for providing this great library, the text rendering results are so good!

**Comment by Chlumsky** [comment]
Thanks, I have fixed it.
