### ISSUE TITLE
Incorrect cast in the FontGeometry assignment operator introduced in commit 20776f1

### ISSUE THREAD

**Issue by taki640** [Chlumsky/msdf-atlas-gen#109]
In [line 51](https://github.com/Chlumsky/msdf-atlas-gen/blob/20776f11f68e3ab8842d226f2a9afa9df7b520d1/msdf-atlas-gen/FontGeometry.cpp#L51C9-L51C65) of the FontGeometry copy assignment operator, the kerning map is cast to a vector of GlyphGeometry, causing a crash.

The line:
```
ownGlyphs = (std::vector<GlyphGeometry>&)orig.kerning
````
Should be:
```
ownGlyphs = (std::vector<GlyphGeometry>&)orig.ownGlyphs
```

**Comment by Chlumsky** [comment]
Sorry about that.
