### ISSUE TITLE
Pack glyph atlas into multiple textures as texture 2D array

### ISSUE THREAD

**Issue by eminor1988** [Chlumsky/msdf-atlas-gen#12]
Hi!
Sorry for bad English skill.

I want to pack glyph atlas into multiple textures as texture 2D array.
So I try to add a new member "int textureIndex" into class "GlyphGeometry", and I also try to add the parameter "textureIndex" to "TightAtlasPacker::pack()".
I desire it finally output the attribute "textureIndex" of glyphs into JSON file and load it to render text using texture 2D array.

But "config.emSize" and "config.pxRange" seem to have depended on value of "atlasPacker.getScale()" and "atlasPacker.getPixelRange()" in "main.cpp".
I don't know what should I do if it has multiple value of "atlasPacker"(that means we have multiple value of "atlasPacker.getScale()" ) after I added a loop to generate multiple bitmaps.
And I am not sure I am on the right track or not.

Does anyone can provide me some advice?

Thanks.

**Comment by Chlumsky** [comment]
Please post non-issue questions into discussions.
