### ISSUE TITLE
Feature Request: Support for multiple fonts in a single atlas

### ISSUE THREAD

**Issue by stephanemagnenat** [Chlumsky/msdf-atlas-gen#13]
Hello,

I would be interested in having multiple fonts in a single atlas texture. I can probably contribute towards that, but before starting, I would like to know if there are already plans or even maybe work in that direction?

Thank you, kind regards.

**Comment by Chlumsky** [comment]
Ok, I will do it.

**Comment by saidwho12** [comment]
I did that in my project, you can check on my github, although quite early. It's based on this generator.

**Comment by stephanemagnenat** [comment]
Great! Something that would make sense in that context imho is to be able to specify independently for each font `-charset` and `-glyphset`. For example, in a mobile game/app, one might want to use Roboto as the main font but also Material Icons, which is an icon font whose entries are specified by ligatures, and therefore in the context of `msdf-atlas-gen` entries would have to referred by their glyph number.

**Comment by Chlumsky** [comment]
I have implemented this in the branch `multi-font` (6649e2b). Please let me know if it is to your satisfaction.

**Comment by stephanemagnenat** [comment]
Thanks a lot, your work is extremely helpful! I've just started testing, so far it works great!

Maybe one missing feature is that the name of the font is lost (it was already before, but it did not matter so much as there was only one font). Maybe some information from the [name table](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=iws-chapter08#3054f18b) could be added to each variant? I'm imagining the most useful would be "1, Font Family name." and "2, Font Subfamily name.", but maybe it is easier to dump all non-empty fields in a generic way.

**Comment by Chlumsky** [comment]
How about if you had to supply that info yourself so that you wouldn't rely on the metadata being filled in in a predictable way, for example:

```
-font arial.ttf -fontname "Arial" -and -font arialbd.ttf -fontname "Arial Bold"
```

Would that be sufficient?

**Comment by stephanemagnenat** [comment]
Yes, it seems a very reasonable solution!

**Comment by Chlumsky** [comment]
Done.

**Comment by stephanemagnenat** [comment]
Thank you very much, it works like a charm!
