### ISSUE TITLE
Feature Request: Support Y origin top

### ISSUE THREAD

**Issue by igaryhe** [Chlumsky/msdf-atlas-gen#15]
I'm trying to integrate this awesome tool into the game engine I'm making. I found that in the output JSON file, there is an attribute of `"atlas"` listed as `"yOrigin": "bottom"`, and it seems like this is hardcoded in the original C++ code. It would be better if the tool could receive the Y origin direction as a command-line parameter since the graphics API I'm working with has the top side of the texture as the Y origin and this gives users enough flexibility.

**Comment by HurricanKai** [comment]
It's pretty easy to convert this in my experience. For the atlas bounds I just swap Top and Bottom and subtract them from the image height.

**Comment by Chlumsky** [comment]
Alright, I have added this now.
