### ISSUE TITLE
Feature request: Add padding parameter

### ISSUE THREAD

**Issue by ivanpopelyshev** [Chlumsky/msdf-atlas-gen#19]
Subj, usually texture packer apps accept padding param between symbols so shader is easier to code, simple `clamp()` is not enough if I draw want to draw the letter with spacing, for example when i want to scale it

Thanks for awesome lib btw!

**Comment by Chlumsky** [comment]
I'm sorry, but I didn't understand your example. Can you explain more clearly a use case where padding is required?

**Comment by ivanpopelyshev** [comment]
I had this picture, then I added extra clamping that fixed it.

![image](https://user-images.githubusercontent.com/695831/123540547-3878f380-d748-11eb-80e4-1c87a10d2df5.png)

But now i tried to reproduced it again, and it turned out I actually had mipmaps turned on :)

Never mind then.
