### ISSUE TITLE
API Clarifications

### ISSUE THREAD

**Issue by weichx** [Chlumsky/msdf-atlas-gen#2]
A few things came up for me when trying to use this package and I was hoping someone could lend a hand. I'm using the JSON output and am confused about the `planeBounds` and `atlasBounds` fields. I think atlas bounds are the pixel space coordinates in the texture for a given glyph and I can calculate uvs using atlasBounds divided by atlas dimensions. Is this correct?

Secondly I have no idea what `planeBounds` is for, I was looking for a description in the docs but didn't see anything. Could you give me a quick explaination?

Lastly, I'm trying to figure out the relationship between `emRange`, `pixelRange`, and size in ems. What I'd like to do is generate a font at a given point size but after tinkering a while I didn't figure out how to do this, could you please point me in the right direction? 

Thanks! By the way I'm really impressed with the atlas generation performance, Unity's TextMeshPro takes up to 30 seconds to build an atlas but msdf-atlas-gen is around 100ms for the same font.

**Comment by Chlumsky** [comment]
You are correct about `atlasBounds`, by dividing by the atlas dimensions, you get the texture coordinates. The `planeBounds` are for positioning the glyphs in the output "plane" (I couldn't come up with a better term), that is, where to put the textured rectangle when typesetting the text, relative to the baseline "cursor" that then moves by `advance` to the right. This tells you for example that the character `y` should be positioned lower than `Y` even though they might have similar height.

As for the units, font size (`-size`) is specified as pixels per EM, the size of an EM is taken from the font file's metadata, and this should be the same as the `px` font size unit in CSS. I believe the conversion rate for point size is simply *1px = 0.75pt*, so you just have to multiply your point size by 4/3. The `-emrange` and `-pxrange` values specify the width of the range of representable distances in either unit, I am not sure what is unclear about these.

**Comment by weichx** [comment]
Great, that's really helpful and should be enough for me to continue working with this. Thanks a lot
