### ISSUE TITLE
Packaging in conan

### ISSUE THREAD

**Issue by Sahnvour** [Chlumsky/msdf-atlas-gen#23]
Thanks for this tool.

Would you be interested in packaging it for conan ? I'm using conan as my package manager for C++, and it would be nice to have access to msdf-atlas-gen there, for easy integration in build systems. Also conan-center provides prebuilt binaries of packages for a lot of different configurations which is handy.
[msdfgen](https://conan.io/center/msdfgen) is already packaged for example.

I think this might need a small rework of the build script, for example a move to CMake.

**Comment by Chlumsky** [comment]
Never heard of it, so not really.

**Comment by Sahnvour** [comment]
I may have a go at it eventually, is this something you'd accept as a PR though ?

**Comment by Chlumsky** [comment]
If it's just a CMake file and it's done properly, probably yes, but not if it involves some other bloat or if you try to delete my VS project files.

**Comment by Jairard** [comment]
If you're still OK with this @Chlumsky , I'll pick up the work from here and propose a PR asap.

**Comment by Jairard** [comment]
CMake support was added in ae40bf4a3a0fd4a31ba278bacd1413a1da4d73cf.
@Chlumsky would you please consider adding a version tag at this commit ? It would make packaging nicer.

**Comment by Chlumsky** [comment]
Does it have to be a release or just a tag?

**Comment by Jairard** [comment]
It has to be an official release.
If it's not, I can use the archive from the latest commit and a special conan format to specify the version, but it's less nice, so as you prefer.

**Comment by Chlumsky** [comment]
Then you'd have to wait until monday when I get home, because I'd rather not build the official release binaries on a different computer where I don't have it set up properly.

**Comment by Chlumsky** [comment]
@Jairard I have made the release.

**Comment by Jairard** [comment]
Great, thank you !
I'll proceed to make the PR on conan repo and post an update when the package is available.

**Comment by Jairard** [comment]
The package is now available on conan center: https://conan.io/center/msdf-atlas-gen
