### ISSUE TITLE
Msdfgen includes don't contain `msdfgen` folder

### ISSUE THREAD

**Issue by Jairard** [Chlumsky/msdf-atlas-gen#25]
Hi,

I noticed that msdfgen includes, such as [this one](https://github.com/Chlumsky/msdf-atlas-gen/blob/3ff9b0525422e718658637e27a1fb9d0954538fc/msdf-atlas-gen/AtlasStorage.h#L4) are like `<msdfgen.h>` and not `<msdfgen/msdfgen.h>`.

If I am not mistaken, the `msdfgen` cmake does nto provide access to this kind of include (inferred from [this line](https://github.com/Chlumsky/msdfgen/blob/1b3b6b985094e6f12751177490add3ad11dd91a9/CMakeLists.txt#L63) but I am no really good with cmake so I might have missed something). It seems to work here because of how git submodules work and the manual `-I msdfgen` in the makefile.

Would you be interested in a PR to change that ? I actually need it to integrate this repo to conan package system, but it can be done externally so this modification is not necessary on my side, but I figured you might want to have it here too.

**Comment by Chlumsky** [comment]
`#include <msdfgen.h>` is the correct way to include the library in other projects and the include directory configuration should reflect that.

**Comment by Jairard** [comment]
Ok, I will make a PR to fix this.
I also noticed that there is a `#include <lodepng.h>` in [`image-encode.cpp`](https://github.com/Chlumsky/msdf-atlas-gen/blob/3ff9b0525422e718658637e27a1fb9d0954538fc/msdf-atlas-gen/image-encode.cpp#L4). This header is in the folder `mdsfgen/include`, but is considered as a private header of `msdfgen-ext` in the [CMakeLists.txt](https://github.com/Chlumsky/msdfgen/blob/1b3b6b985094e6f12751177490add3ad11dd91a9/CMakeLists.txt#L37).
What would be the correct way to handle this: make the header public (with `ext/*.[h|hpp]`) or include it differently from this repo ?

**Comment by Chlumsky** [comment]
I guess this repo should have `msdfgen/include` in its include directories.
