### ISSUE TITLE
Cannot build on m1 macbook, 'tf2build.h' not found

### ISSUE THREAD

**Issue by maladr0it** [Chlumsky/msdf-atlas-gen#38]
On an m1 macbook, I cloned the repository recursively, and ran `make`

The following error is printed
```
msdfgen/ext/import-font.cpp:6:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^~~~~~~~~~~~
1 error generated.
```

Using the cmake GUI, it reports to me:
```
Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
```

I have tried installing freetype via `brew install freetype`, and modifying the Makefile to point freetype like so:
```
-I /opt/homebrew/include/freetype2
```
This instead produces the error:
```
ld: library not found for -lfreetype
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I believe macOS should already include the freetype library anyway.

I have successfully built this library on other macOS machines, so I'm not sure if I'm doing something wrong or there is something unique about my setup that is causing this issue.

**Comment by Chlumsky** [comment]
The build now requires CMake and has been overhauled. Please reopen if the issue persists.
