### ISSUE TITLE
No Kerning from FreeType

### ISSUE THREAD

**Issue by gurki** [Chlumsky/msdf-atlas-gen#4]
Hi Viktor, awesome work on these libs and the idea behind them!

I've been working with it over the last couple days and can't seem to get any kerning results, the list in e.g. a converted json output is always empty. I dug in and it seems the `FT_Get_Kerning()` call in [msdfgen](https://github.com/Chlumsky/msdfgen/blob/5b5272e7a8bd71a6c7f55951659df69a355486c8/ext/import-font.cpp#L166) always yields zero kerning. I tried updating FT to their latest version as well, to no success. Any clues why this is the case? Wasn't able to root-cause it.

Cheers and all the best!

**Comment by Chlumsky** [comment]
Are you sure the font actually has kerning pairs? If the FT call returns zero but shouldn't, then maybe you need to submit the issue to FreeType developers.

**Comment by gurki** [comment]
Thanks for the quick reply! I've tried several fonts with kerning (e.g. [Source Sans Pro](https://fonts.google.com/specimen/Source+Sans+Pro)) and verified the font converting it using [other tools](https://msdf-bmfont.donmccurdy.com/). Seems like a "doesn't work on my machine"-thing then I suppose. I'll reach out to the FreeType devs and will update this issue when there's a resolution. Cheers.

**Comment by jnhyatt** [comment]
FreeType [doesn't support every time of kerning](https://www.freetype.org/freetype2/docs/tutorial/step2.html#section-3). Maybe compile a simple FreeType program that reads in the files and prints the kerning values?

**Comment by stephanemagnenat** [comment]
> Maybe compile a simple FreeType program that reads in the files and prints the kerning values?

The program `ttfdump` wight help with that. I just run across a similar problem. I guess the problem might be that the font only have `GPOS` table and not the `kern` table (it's the case with Roboto for example). It seems that Freetype does not support the `GPOS` table. A work around is to open the font in [fontforge](https://fontforge.org/) and [re-export it with `kern` table](https://graphicdesign.stackexchange.com/questions/126786/how-to-export-font-with-kern-tables-and-not-gpos-tables-using-fontforge). I hope it helps!
