### ISSUE TITLE
Feature Request: CSV + JSON format

### ISSUE THREAD

**Issue by jeremyabel** [Chlumsky/msdf-atlas-gen#50]
I like CSV for keeping the glyph data as it's much more space-efficient than json, however this means the font data (atlas and metrics fields) gets discarded. It'd be nice to be able to output both a CSV with the glyph data, and a JSON file with the metrics. Or maybe two csv files?

**Comment by Chlumsky** [comment]
You can have both outputs generated in a single invocation, although most of the data will be duplicated. Is that not sufficient? A very simple script could then be used to remove the redundant data from the JSON file.

**Comment by jeremyabel** [comment]
Ahhhh I forgot about the `and` flag, good point.

**Comment by Chlumsky** [comment]
`-and` flag is for multiple fonts, just use both output arguments.

**Comment by jeremyabel** [comment]
ahhhh ok, that's much more clear, thanks!
