### ISSUE TITLE
Documentation for json, csv output

### ISSUE THREAD

**Issue by Phildo** [Chlumsky/msdf-atlas-gen#7]
Is there anywhere I can go to help make sense of the output layout data?

for example, I have this output regarding the character 'A':

```
    {"unicode":65,"advance":0.63300000000000001,
      "planeBounds":{"left":0.0023802681992336704,"bottom":-0.032253256704980887,"right":0.63011973180076619,"top":0.77125325670498079},
      "atlasBounds":{"left":0.5,"bottom":43.5,"right":25.5,"top":75.5}
    },
```

`unicode` is self explanatory,
`advance` is, I assume, the proportional-to-font-size distance to advance the cursor for the next character
`planeBounds` I assume are the bounds of the glyph on a [-1,1] plane (for both X and Y)? However, if that were the case, looking at my output image I would expect the bounds for 'A' to be something along the lines of `"left":-1,"bottom":-0.7,"right":0.1,"top":-0.5`, which it isn't even close to...
`atlasBounds` I assume would have been similar to `planeBounds`, but in pixel coordinates?

Any help and I'd happily contribute a blurb to your README!

Thanks for your work!

**Comment by Chlumsky** [comment]
`planeBounds` are world coordinates relative to cursor, `atlasBounds` are coordinates for the atlas cutout, see #2.

**Comment by wyatthuckaby** [comment]
I'm having issues where the atlasBounds end up on the complete wrong character. or just in the middle of space in the font.

**Comment by Chlumsky** [comment]
@wyatthuckaby  You didn't provide much information to go on, but one possible explanation that comes to mind is that perhaps you expect the Y-axis to originate at the top? By default, it goes from the bottom up like in OpenGL. Try `-yorigin top`

**Comment by wyatthuckaby** [comment]
@Chlumsky 

Take for instance this atlas map:
![notosans](https://user-images.githubusercontent.com/11396340/168641877-0bb9f2fe-1ce8-4a8f-b7df-03d9307aed9d.png)

at unicode 82 ('R') the following atlas bounds are provided:
`            
"atlasBounds": {
                "left": 125.5,
                "bottom": 89.5,
                "right": 144.5,
                "top": 114.5
}
`
OpenGL texture coordinates operate from the bottom left, which in this case, places the start point somewhere on top of H. This clearly does not reflect the actual atlas location of the letter.

**Comment by Chlumsky** [comment]
Huh? The bottom of R is literally 89 pixels from the bottom edge.

**Comment by DennisGruendig** [comment]
It really is a little confusing, as mixing different coordinate spaces always is.
If the Y axis is inverted, you must not only switch top and bottom values, but also substract from the screen height and add the relative distance to the baseline / cursor as mentioned above.

![grafik](https://github.com/Chlumsky/msdf-atlas-gen/assets/86776302/cf091752-0097-4f44-ab40-c98130f910ef)

I was aiming for the D when I realized, the coordinates of the atlas-gen are from bottom to top.

So atlas_height - glyph_bottom - glyph_height (glyph_top - glyph_bottom) gives the right height.
