### ISSUE TITLE
Feature request: add font name into json in metrics section

### ISSUE THREAD

**Issue by jabamaus** [Chlumsky/msdf-atlas-gen#71]
I'd like to add multiple fonts into a single atlas and export the metrics to json. I'm then going to write a tool to convert this to C code. I need the font name in there to be able to identify the font.

Thanks :)

**Comment by Chlumsky** [comment]
Use the `-fontname` parameter to set an identifier for each font.

**Comment by jabamaus** [comment]
Ah sorry. I thought that was an odd omission!
