### ISSUE TITLE
Border /Edge bleeding issue

### ISSUE THREAD

**Issue by BastianZuehlke** [Chlumsky/msdf-atlas-gen#72]
I have created a MSDF 
msdf-atlas-gen-master bastianzuhlke$ ./bin/msdf-atlas-gen -pxrange 0 -font OpenSans-Regular-V2.ttf -charset charset.txt -size 36 -format bin -imageout OpenSans-Regular-V2.raw -json OpenSans-Regular-V2.json -pots -type msdf
When I render the word Lorem I get a dark grey line left from the "L". I can see that in the atlas left to the "L" is the "M".
So I suppose that the shader is fetching texels belonging to the M. 

"L"
"atlasBounds": {
        "left": 73.5,
        "bottom": 95.5,
        "right": 90.5,
        "top": 123.5
      }

"M"
      "atlasBounds": {
        "left": 44.5,
        "bottom": 95.5,
        "right": 72.5,
        "top": 123.5
      }

No MipMap is used. 
TEXTURE_MAG_FILTER -> Linear
TEXTURE_MIN_FILTER -> Linear

The atlas is 256x256. To calculate the uvs I am diving the left / bottom / right / top with 256.
In general such border lines appear here and then.

If i am using an atlas generated by msdf-bmfont-xml which offers texturePadding I do not have these artefacts. Unfortunately msdf-bmfont-xml has some flaws why I can not use it.

Any idea to avoid this issue ?

**Comment by BastianZuehlke** [comment]
My bad. Found the issue.

**Comment by Dragoy** [comment]
Can you tell me what the problem was, because I'm getting them in my atlas too :( 

![Image](https://github.com/user-attachments/assets/66224c6e-8570-4e87-bf3f-68e1af68525d)
