### ISSUE TITLE
Export all glyphs instead of user-defined subset

### ISSUE THREAD

**Issue by BaddestBoss123** [Chlumsky/msdf-atlas-gen#77]
`The atlas generator loads a subset of glyphs from a TTF or OTF font file`

that's nice, but I'm not picky and just want access to all glyphs. is there a way to do this?

already tried charset.txt with `[0, 1114111]` in it but the resulting image looked completely broken

**Comment by TrevorCow** [comment]
I think it has to be given as hex. Try `[0x0,0xFFFF]` instead

**Comment by Chlumsky** [comment]
Implemented in f1ad23f7c4dd14b310de0f86780925ece016796b
