### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by maatko** [Chlumsky/msdf-atlas-gen#79]
Make is so you can specify padding between glyphs in the atlas

Pull request that adds this feature:
https://github.com/Chlumsky/msdf-atlas-gen/pull/80

**Comment by jay3d** [comment]
![image](https://github.com/Chlumsky/msdf-atlas-gen/assets/2527637/8fa81a37-963c-498b-bcd2-08ab8b425dba)

I have also noticed when using MSAA framebuffer, texture lookups do introduce artifacts, which padding can greatly help in those situations.

**Comment by Chlumsky** [comment]
@jay3d No, they do not. Your texture coordinates are wrong.

**Comment by jay3d** [comment]
@Chlumsky This only happens with MSAA framebuffers, texture coords are taken from the generated json description.

**Comment by Chlumsky** [comment]
Ok, you might be right. However, I am already working on the padding feature and it will be available before the end of April.

**Comment by jay3d** [comment]
But if there's a solution currently without the padding feature, I would love to know it, I'll post how I'm processing the UVs, so you might spot something unusual that I couldn't:

```cpp
if ( const auto atlasBounds = glyph.find( "atlasBounds" ) )
{
    const auto atlasBoundsLeft   = ( *atlasBounds )[ "left" ].asDouble();
    const auto atlasBoundsBottom = ( *atlasBounds )[ "bottom" ].asDouble();
    const auto atlasBoundsRight  = ( *atlasBounds )[ "right" ].asDouble();
    const auto atlasBoundsTop    = ( *atlasBounds )[ "top" ].asDouble();
    uvs.x() = atlasBoundsLeft / atlasWidth;
    uvs.y() = atlasBoundsBottom / atlasHeight;
    uvs.z() = ( atlasBoundsRight - atlasBoundsLeft ) / atlasWidth;
    uvs.w() = ( atlasBoundsTop - atlasBoundsBottom ) / atlasHeight;
}
```

Then it's passed to the vertex shader:

```glsl
outUv = vec2( uvs.x + inUv.x * uvs.z, uvs.y + inUv.y * uvs.w )
      * vec2( 1.0f, -1.0f ) + vec2( 0.0f, 1.0f );                                                   
```
Where `inUv` are the normalized plane texture coords.

**Comment by Chlumsky** [comment]
Padding added in 2588a2a.
