### ISSUE TITLE
New Release for Dynamic Atlas?

### ISSUE THREAD

**Issue by rconde01** [Chlumsky/msdf-atlas-gen#86]
The sample code for dynamic atlas doesn't work with 1.2.2 - could you do a newer release with that functionality?

**Comment by Chlumsky** [comment]
But the releases are only for the CLI?

**Comment by rconde01** [comment]
fair - i guess it doesn't need a release, but a tag so that packages can reference a number instead of a hash, which works - but is a bit awkward.

**Comment by Chlumsky** [comment]
New version released.
