### ISSUE TITLE
Why this all dlls are needed?

### ISSUE THREAD

**Issue by dreaw131313** [Chlumsky/msdf-atlas-gen#93]
When I build this library with CMAKE and vcpkg and want link it as static library to my project I must add this dynamic libraries:
brotlicommon.dll
brotlidec.dll
bz2.dll
freetype.dll
libpng16.dll
zlibd1.dll
Is there any way to buid it to one static library without need for this dynamics? Or am I stupid and do not understand something?

**Comment by Chlumsky** [comment]
If you set `VCPKG_TARGET_TRIPLET` to a static one (such as `x64-windows-static`) and `BUILD_SHARED_LIBS` to `OFF` (default), it definitely shouldn't require any DLL's, although you will still need to link the static versions of the same libraries.

**Comment by Chlumsky** [comment]
Feel free to reopen this issue if you still have this problem.
