### ISSUE TITLE
Font file not recognised

### ISSUE THREAD

**Issue by waviation9** [Chlumsky/msdf-atlas-gen#96]
Hello. I am trying to generate a font atlas for a game mod I'm currently working on, but whenever I try to input the filename in the specified field I get this error: `The syntax of the command is incorrect.`
It happened with every font I tried. Not sure if I'm an idiot or if there's a bug.
![image](https://github.com/Chlumsky/msdf-atlas-gen/assets/106398654/d77b5098-ed65-4ea9-b467-ef651b0fee2a)
Can someone please help me with this, I'm almost certain I'm doing something wrong as I'm not quite familiar with console programs (or GitHub for that matter)

**Comment by Chlumsky** [comment]
Don't put in the brackets `<` `>`, they are just to mark the parts that you should replace with your values. If there are spaces in the filename, use quotation marks.

**Comment by waviation9** [comment]
Thank you so much. It worked!
