### ISSUE TITLE
The released windows build contains v1.1, not v1.3

### ISSUE THREAD

**Issue by Longor1996** [Chlumsky/msdf-atlas-gen#99]
As the title says, the released windows build appears to contain the v1.1 binary, not the v1.3 binary; a packaging error/mistake?

https://github.com/Chlumsky/msdf-atlas-gen/tree/v1.3
https://github.com/Chlumsky/msdf-atlas-gen/tree/v1.1

**Comment by Chlumsky** [comment]
Where?

**Comment by Chlumsky** [comment]
@Longor1996 Can you please clarify what exactly you mean? I don't see the issue.

Does anyone else have the same problem?

**Comment by Longor1996** [comment]
Apologies! It turned out to be a env-path conflict between my scoop installation and my standalone tools directory. :(
